### ISSUE TITLE
H29toH24_rename.do について

### ISSUE THREAD

**Issue by daisukeadachi** [Takahiro-Toriyabe/MicroDataCleaning#10]
こんにちは。お世話になっております。最近こちらのページの存在を知り、利用させていただいております。ありがとうございます。

表題の2017年の変数名を2012年のものに変更するdo-fileについてですが、一点質問がありましたので投稿させていただきます。
297行目、`capture rename KC_4_1_JIKI KC_KYOIKU`となっている部分ですが、2017年の就調符号表を確認するに、2012年の変数の定義により近いのは、`KC_4_1_JIKI`ではなく、`KC_4_1_SHUGAKU`ではないでしょうか。
前者は卒業時期、後者は卒業しているかどうかを問うており、2012年の`KC_KYOIKU`に近いのは後者ではないかと考えております。

どの程度オープンに管理されていらっしゃるか分からず、プルリクなどは投げないでこちらのイシューでお伺いしました。ご確認よろしくお願いいたします。

**Comment by Takahiro-Toriyabe** [comment]
@daisukeadachi 
返信が遅くなってしまいすみません。ファイルを確認しましたがご指摘の通りだと思います。

個々のデータの読み込みとラベル付けはほぼ問題ないのですが、調査年間で変数を揃えるファイルはレイアウト表の変数名や変数の説明の文字列の距離を測ってマッチングしているので、残念ながらあまり精度はよくありません。

修正後のファイルのプルリクをお願いできませんでしょうか？

よろしくお願いいたします。

**Comment by Takahiro-Toriyabe** [comment]
@daisukeadachi 
プルリクエストありがとうございます！
