### ISSUE TITLE
労働力調査

### ISSUE THREAD

**Issue by AyakoKondoUTISS** [Takahiro-Toriyabe/MicroDataCleaning#9]
@Takahiro-Toriyabe 
do-fileに入ってるほかの統計のいろいろと使わせていただいてます。
労働力調査のdofileあるけどいりますか？

**Comment by Takahiro-Toriyabe** [comment]
@AyakoKondoUTISS 
ありがとうございます！
労働力調査のdo-fileはまだないのでいただけますと幸いです。
